### ISSUE TITLE
More fair comparasion

### ISSUE THREAD

**Issue by zero-suger** [Ali-Fayzi/face-recognition#13]
First of all good job, but I think in Retina to compare with other face detection models you have to use different backbone. Because your testing times is slower but more accuracy. I believe that if you test with image which has a lot of faces with different face alignments Retina will get the most accuracy. Becuase in your testing your are using Retina with backbone Resnet50 (96~ MB). I recommend using mobilenet0.25 (1.7~ MB) and then you will get less testing time and it is more fair comparison. Cascade, MTCNN, not accurant in WILD case. Please try with different backbone and also add 'SCRFD' face detection too (one of the latest). 

Good luck (:

**Comment by Ali-Fayzi** [comment]
Hi, thank you for the very helpful points you mentioned. I'll try to incorporate the mentioned points and also add "SCRFD" as a new face detection model.

Best of luck!

**Comment by Ali-Fayzi** [comment]
@zero-suger 
According to what was mentioned, I tested MobileNet0.25 and ResNet50 for RetinaFace, and you can see the outputs in the image below. My settings for both were as follows:
Confidence Threshold: 0.1
Keep Top K: 750
NMS (Non-Maximum Suppression) Threshold: 0.4
Top K: 5000

![retina_mobilenet0 25](https://github.com/Ali-Fayzi/face-recognition/assets/88140027/74d8bab8-4e1c-4c66-ad26-b17f7307d18b)
![retina_resnet50](https://github.com/Ali-Fayzi/face-recognition/assets/88140027/441c5c4b-e3b7-4f39-b637-ddc3b9358639)

As you can see in the above image, the detection accuracy of MobileNet0.25 is lower compared to ResNet50 in challenging images.

**Comment by zero-suger** [comment]
Yeap, of course : (cz Retina is heavy model, with huge number of params than mobilenet05)
Based on requirements u can use one of them . 

1) wanna increase acc. decrease threshold. 
2)wanna compare with other models set all FD models Threshold to 0.4 

Good luck 
Thks to share and discuss (:

**Comment by Ali-Fayzi** [comment]
You're welcome. Thank you for the your attention.

**Comment by Ali-Fayzi** [comment]
You're welcome. Thank you for your attention.
